name       : libqmi
version    : 1.30.2
release    : 13
source     :
    - https://www.freedesktop.org/software/libqmi/libqmi-1.30.2.tar.xz : be01ece0ea2c2194cbea5744bf5aaf06c04ba5fb7ec7887a13116c76d114fedd
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : WWAN modem (QMI) protocol library
description: |
    libqmi is a glib-based library for talking to WWAN modems and devices which speak the Qualcomm MSM Interface (QMI) protocol.
builddeps  :
    - pkgconfig(mbim-glib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
