name       : libqmi
version    : 1.20.2
release    : 6
source     :
    - https://freedesktop.org/software/libqmi/libqmi-1.20.2.tar.xz : c73459ca8bfe1213f8047858d4946fc1f58e164d4f488a7a6904edee25e2ca44
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : WWAN modem (QMI) protocol library
description: |
    libqmi is a glib-based library for talking to WWAN modems and devices which speak the Qualcomm MSM Interface (QMI) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
