name       : libqmi
version    : 1.24.6
release    : 10
source     :
    - https://www.freedesktop.org/software/libqmi/libqmi-1.24.6.tar.xz : 1325257bc16de7b2b443fa689826c993474bdbd6e78c7a1e60e527269b44d8c9
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : WWAN modem (QMI) protocol library
description: |
    libqmi is a glib-based library for talking to WWAN modems and devices which speak the Qualcomm MSM Interface (QMI) protocol.
builddeps  :
    - pkgconfig(mbim-glib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
