name        : libqmi
version     : 1.12.6
release     : 3
source     :
    - http://www.freedesktop.org/software/libqmi/libqmi-1.12.6.tar.xz : 0857bffece4e8ddfa7f721dd9ca63b4c78de345ac9ae2faebf04062cacba3780
license     :
    - LGPL-2.0+
summary     : WWAN modem (QMI) protocol library
description : |
    libqmi is a glib-based library for talking to WWAN modems and devices which speak the Qualcomm MSM Interface (QMI) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
