name       : libqmi
version    : 1.22.0
release    : 8
source     :
    - https://www.freedesktop.org/software/libqmi/libqmi-1.22.0.tar.xz : 21c198b481f1617bb7edb1960d823569de3e38b269dbf513af1b56048cafaa17
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : WWAN modem (QMI) protocol library
description: |
    libqmi is a glib-based library for talking to WWAN modems and devices which speak the Qualcomm MSM Interface (QMI) protocol.
builddeps  :
    - pkgconfig(mbim-glib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
