name       : libqmi
version    : 1.20.0
release    : 5
source     :
    - https://www.freedesktop.org/software/libqmi/libqmi-1.20.0.tar.xz : 21428cd3749c56246565123f707fee51238651a22c60bdc85ebce97388626eb4
license    :
    - GPL-2.0
    - LGPL-2.1
component  : network.base
summary    : WWAN modem (QMI) protocol library
description: |
    libqmi is a glib-based library for talking to WWAN modems and devices which speak the Qualcomm MSM Interface (QMI) protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
